swagger: "2.0"
info:
  title: Textifai API
  description: API for handling document uploads and processing.
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - http
paths:
  /upload:
    post:
      summary: Uploads a PDF document.
      description: Endpoint to accept PDF document uploads for text analytics.
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: file
          type: file
          description: The file to upload.
          required: true
      responses:
        200:
          description: Successful upload
          # Add any relevant schema details here if you return specific data in the response

