name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies in shared package
        run: yarn workspace @textifai/shared install

      - name: Build shared package
        run: yarn workspace @textifai/shared build

      - name: Install dependencies in web package
        run: yarn workspace @textifai/web install

      - name: Build web package
        run: yarn workspace @textifai/web build

      - name: Test web package
        run: yarn workspace @textifai/web test

  containerize:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/123123123/locations/global/workloadIdentityPools/the-workload-pool/providers/the-provider
          service_account: githubactions@textifai-g5njdml004.iam.gserviceaccount.com
